spring:
  application:
    name: customer-microservice
  cloud:
    config:
      profile: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}